version: '3'

services:
  docs:
    image: industry_ai_agents_local_docs
    container_name: industry_ai_agents_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./industry_ai_agents:/app/industry_ai_agents:z
    ports:
      - '9000:9000'
    command: /start-docs
